name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        env:
            APP_ENV: behat
            DB_HOST: localhost
            DB_TYPE: mysql
            DB_ROOT_PASSWORD: root
            DB_EZ_USER: ezp
            DB_EZ_PASSWORD: ezp
            DB_EZ_DATABASE: behattestdb
        strategy:
            fail-fast: false
            matrix:
                # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners for available os versions
                include:
                    - config-file: '.euts.3.0.env'
                      operating-system: 'ubuntu-20.04'
                      code-coverage: ~
                    - config-file: '.euts.3.1.env'
                      operating-system: 'ubuntu-20.04'
                      code-coverage: ~
                    - config-file: '.euts.3.2.env'
                      operating-system: 'ubuntu-22.04'
                      code-coverage: codecov
                    - config-file: '.euts.3.3.env'
                      operating-system: 'ubuntu-22.04'
                      code-coverage: ~
        steps:
            -   name: checkout code
                uses: actions/checkout@v2

            # Although this action is useful, we prefer to use the same script to set up php that we use for the
            # docker image used for local testing. This allows us to make sure that the script is always in good shape
            #-
            #    uses: shivammathur/setup-php@v2
            #    with:
            #        php-version: ${{ matrix.php }}
            #        extensions: curl, dom, mbstring, xsl
            #        ini-values: 'cgi.fix_pathinfo=1, always_populate_raw_post_data=-1'
            #        #tools: phpunit/phpunit:a_version_compatible_with_php_5.3-5.5
            #        # NB: this disables xdebug completely
            #        coverage: none

            # @todo avoid downloading composer deps on every workflow. Is this useful/working for us?
            #-
            #    uses: actions/cache@v2
            #    with:
            #        path: /tmp/composer-cache
            #        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            # @todo stop any unused service and process to save ram/cpu: php-fpm (esp. if a != php version), docker,
            #       containerd, snapd, ModemManager?, pakagekit?, xsp4.exe

            -   name: set up the test stack and run tests
                uses: tanoconsulting/euts@0.9.0
                with:
                    configuration-file: Tests/environment/${{ matrix.config-file }}
                    code-coverage-service: ${{ matrix.code-coverage }}
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

            -   name: troubleshoot
                if: ${{ failure() }}
                run: |
                    #env
                    #php -i
                    #systemctl list-units --all --type=service --no-pager | grep running
                    #ps auxwww
                    #dpkg --list | grep php
                    #pwd
                    #sudo env
                    #ls -ltr /var/log
                    sudo cat /var/log/php*.log
